version: "3.7"
services:
  tender_hack_web:
    image: tender_hack_web
    container_name: tender_hack_web
    command: ./docker/gunicorn.sh --log-level debug
    network_mode: "host"
    restart: always

    build:
      context: .
      dockerfile: ./docker/Dockerfile

    volumes:
      - ./gunicorn_socket:/gunicorn_socket
      - ./static_files:/server/static
      - ./media_files:/server/media
      - ./logs:/server/logs
      - .:/server
    env_file:
      - ./.env

    depends_on:
      - tender_hack_db

  tender_hack_db:
    container_name: tender_hack_db
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"


volumes:
  static_files:
