# Generated by Django 4.2.6 on 2023-11-18 06:04

import TenderHack.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('external_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('conclusion_datetime', models.DateTimeField(verbose_name='Дата заключения')),
                ('price', models.FloatField(verbose_name='Цена по которой заключен контракт')),
                ('violations', models.BooleanField(default=False, verbose_name='Наличие нарушений срока подписания контракта')),
                ('status', models.CharField(choices=[('finished', 'Исполнен'), ('concluded', 'Заключен'), ('dissolved', 'Расторгнут'), ('refusal_of_conclusion', 'Отказ от заключения')], default='concluded', max_length=255, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Поставщик?')),
                ('is_contractor', models.BooleanField(default=False, verbose_name='Покупатель?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpps', to='TenderHack.company', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='SuspicionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.TextField(null=True, verbose_name='Имя')),
                ('last_change_password_attempt_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки смены пароля')),
                ('password_recovery_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', TenderHack.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('item', models.CharField(max_length=255, verbose_name='Название товара')),
                ('external_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='TenderHack.subdivision', verbose_name='Заказчик')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='TenderHack.region', verbose_name='Регион')),
                ('suspicions', models.ManyToManyField(related_name='tenders', to='TenderHack.suspiciontype', verbose_name='Подозрения')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('start_datetime', models.DateTimeField(null=True, verbose_name='Дата и время начала блокировки')),
                ('end_datetime', models.DateTimeField(null=True, verbose_name='Дата и время окончания блокировки')),
                ('ban_duration', models.DurationField(null=True, verbose_name='Длительность блокировки')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='TenderHack.subdivision', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(blank=True, null=True, verbose_name='Победитель?')),
                ('date_created', models.DateTimeField(verbose_name='Дата публикации')),
                ('price', models.FloatField(verbose_name='Начальная максимальная цена')),
                ('violations', models.BooleanField(default=False, verbose_name='Наличие нарушений по сроку подписания протокола котировочной сессии')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation', to='TenderHack.subdivision', verbose_name='')),
                ('suspicions', models.ManyToManyField(related_name='quotation_sessions', to='TenderHack.suspiciontype', verbose_name='Подозрения')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_sessions', to='TenderHack.tender', verbose_name='Тендер')),
            ],
        ),
        migrations.CreateModel(
            name='CPGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_path', models.CharField(max_length=255, verbose_name='Полный путь')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='TenderHack.cpgs', verbose_name='Родительский КПГЗ')),
            ],
        ),
        migrations.CreateModel(
            name='ContractExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_upd_id', models.IntegerField(verbose_name='ID УПД')),
                ('scheduled_delivery_date', models.DateTimeField(verbose_name='Регламентная дата поставки')),
                ('actual_delivery_date', models.DateTimeField(verbose_name='Фактическая дата поставки')),
                ('delivery_date_delta', models.DurationField(verbose_name='Разница в датах поставки')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='TenderHack.contract', verbose_name='Контракт')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_executions_as_contractor', to='TenderHack.subdivision', verbose_name='Покупатель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_executions_as_supplier', to='TenderHack.subdivision', verbose_name='Поставщик')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_contractor', to='TenderHack.subdivision', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quotation_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='TenderHack.quotationsession', verbose_name='Котировочная сессия'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_supplier', to='TenderHack.subdivision', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='contract',
            name='suspicions',
            field=models.ManyToManyField(related_name='contracts', to='TenderHack.suspiciontype', verbose_name='Подозрения'),
        ),
    ]
