# Generated by Django 4.2.6 on 2023-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0002_remove_tender_item_tenderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsession',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='quotationsession',
            name='price',
        ),
        migrations.AddField(
            model_name='tender',
            name='CPGSs',
            field=models.ManyToManyField(related_name='tenders', to='TenderHack.cpgs', verbose_name='КПГЗ'),
        ),
        migrations.AddField(
            model_name='tender',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='tender',
            name='price',
            field=models.FloatField(null=True, verbose_name='Начальная максимальная цена'),
        ),
    ]
