# Generated by Django 4.2.6 on 2023-11-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0003_cpgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Поставщик?')),
                ('is_contractor', models.BooleanField(default=False, verbose_name='Покупатель?')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_contractor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_supplier',
        ),
        migrations.DeleteModel(
            name='Kpp',
        ),
        migrations.AddField(
            model_name='subdivision',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpps', to='TenderHack.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_contractor', to='TenderHack.subdivision', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_supplier', to='TenderHack.subdivision', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='contractexecution',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_executions_as_contractor', to='TenderHack.subdivision', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='contractexecution',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_executions_as_supplier', to='TenderHack.subdivision', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='quotationsession',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation', to='TenderHack.subdivision', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='supplierban',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='TenderHack.subdivision', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='TenderHack.subdivision', verbose_name='Заказчик'),
        ),
    ]
