# Generated by Django 4.2.6 on 2023-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0003_remove_quotationsession_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsession',
            name='violations',
        ),
        migrations.AddField(
            model_name='tender',
            name='violations',
            field=models.BooleanField(default=False, verbose_name='Наличие нарушений по сроку подписания протокола котировочной сессии'),
        ),
    ]
