# Generated by Django 4.2.6 on 2023-11-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0004_remove_quotationsession_violations_tender_violations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='quotation_session',
        ),
        migrations.AddField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='TenderHack.tender', verbose_name='Тендер'),
            preserve_default=False,
        ),
    ]
