# Generated by Django 4.2.6 on 2023-11-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0005_remove_contract_quotation_session_contract_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='TenderHack.tender', verbose_name='Тендер'),
        ),
    ]
