# Generated by Django 4.2.6 on 2023-11-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0005_company_date_created_subdivision_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspicionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='suspicions',
            field=models.ManyToManyField(related_name='contracts', to='TenderHack.suspiciontype', verbose_name='Подозрения'),
        ),
        migrations.AddField(
            model_name='quotationsession',
            name='suspicions',
            field=models.ManyToManyField(related_name='quotation_sessions', to='TenderHack.suspiciontype', verbose_name='Подозрения'),
        ),
        migrations.AddField(
            model_name='tender',
            name='suspicions',
            field=models.ManyToManyField(related_name='tenders', to='TenderHack.suspiciontype', verbose_name='Подозрения'),
        ),
    ]
