# Generated by Django 4.2.6 on 2023-11-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0006_alter_contract_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractexecution',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='TenderHack.contract', verbose_name='Контракт'),
        ),
    ]
