# Generated by Django 4.2.6 on 2023-11-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0007_alter_contractexecution_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tenderitem',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
