# Generated by Django 4.2.6 on 2023-11-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0008_alter_tender_name_alter_tenderitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='creation_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время создания'),
        ),
    ]
