# Generated by Django 4.2.1 on 2023-11-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderHack', '0009_subdivision_creation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='date_delta',
            field=models.DurationField(null=True, verbose_name='Разница'),
        ),
    ]
